### PR TITLE
In case we want to use an object not a class

### PR DESCRIPTION
**Pull request by albulescu**

### CODE REVIEW

**Comment by rubenv** [comment]
What exactly does this patch do?

Do you have an example of something that doesn't work without it?

**Comment by albulescu** [comment]
If i give it just an object doesn't work because has no prototype:

var MyManager = { foo : function() { } };
eventEmitter.inject(MyManager);

**Comment by rubenv** [comment]
Fair enough. Could you add a unit test?

**Comment by albulescu** [comment]
The tests pushed

**Comment by rubenv** [comment]
Great, merging. Thanks a lot!

**Comment by rubenv** [comment]
Released `angular-tiny-eventemitter@1.0.0`

**Pull request merged**
